title: Welcome...
description: Hi, Myself Arun Shal U B. I am currently working as an Assistant Professor in the Department of Mechanical Engineering at College of Engineering Thalassery, Kannur, Kerala.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
