title: Welcome...
description: Hi, myself Arun Shal U. B, Assistant Professor of Mechanical Engineering, College of Engineering Thalassery.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
